Use RedResQ
Go

INSERT INTO Location (country, city, postalCode) VALUES
('Germany', 'Munich', '80331'),
('United States', 'Los Angeles', '90001'),
('France', 'Paris', '75001'),
('Italy', 'Rome', '00118'),
('Japan', 'Tokyo', '160-0022'),
('United Kingdom', 'London', 'WC2N'),
('Australia', 'Sydney', '2000'),
('Canada', 'Toronto', 'M5V 3L9'),
('Spain', 'Barcelona', '08002'),
('Brazil', N'São Paulo', '01310-200'),
('India', 'Mumbai', '400001'),
('China', 'Beijing', '100006'),
('Russia', 'Moscow', '101000'),
('South Africa', 'Johannesburg', '2000'),
('Mexico', 'Mexico City', '06000'),
('South Korea', 'Seoul', '04533'),
('Nigeria', 'Lagos', '100001'),
('Argentina', 'Buenos Aires', 'C1002'),
('Turkey', 'Istanbul', '34000');

INSERT INTO Language (name) VALUES
('English'),
('German'),
('French'),
('Italian'),
('Japanese'),
('Spanish'),
('Chinese'),
('Russian'),
('Portuguese'),
('Hindi'),
('Arabic'),
('Bengali'),
('Punjabi'),
('Korean'),
('Turkish'),
('Dutch'),
('Swedish'),
('Greek'),
('Thai'),
('Vietnamese');

INSERT INTO Image (source) VALUES
('https://example.com/image1.jpg'),
('https://example.com/image2.jpg'),
('https://example.com/image3.jpg'),
('https://example.com/image4.jpg'),
('https://example.com/image5.jpg'),
('https://example.com/image6.jpg'),
('https://example.com/image7.jpg'),
('https://example.com/image8.jpg'),
('https://example.com/image9.jpg'),
('https://example.com/image10.jpg'),
('https://example.com/image11.jpg'),
('https://example.com/image12.jpg'),
('https://example.com/image13.jpg'),
('https://example.com/image14.jpg'),
('https://example.com/image15.jpg'),
('https://example.com/image16.jpg'),
('https://example.com/image17.jpg'),
('https://example.com/image18.jpg'),
('https://example.com/image19.jpg'),
('https://example.com/image20.jpg');

INSERT INTO Quiz (name, maxScore) VALUES
('Math', 20),
('Science', 25),
('History', 30),
('Literature', 15),
('Geography', 25),
('Biology', 20),
('Chemistry', 20),
('Physics', 25),
('Music', 15),
('Art', 15),
('Sports', 20),
('General Knowledge', 30),
('Technology', 25),
('Politics', 20),
('Economics', 20),
('Languages', 15),
('Movies', 25),
('TV Shows', 25),
('Mythology', 20),
('Food', 15);

INSERT INTO Question (text, QuizID) VALUES
('What is 2 + 2?', 1),
('What is the capital of France?', 5),
('Who wrote "Romeo and Juliet"?', 4),
('What is the powerhouse of the cell?', 6),
('Who is the first President of the United States?', 3),
('What is the chemical symbol for water?', 7),
('What is the speed of light?', 8),
('Who painted the Mona Lisa?', 10),
('What is the national sport of Canada?', 11),
('What is the tallest mountain in the world?', 5),
('What is the boiling point of water?', 7),
('What is the currency of Japan?', 3),
('Who composed the "Moonlight Sonata"?', 9),
('Who discovered penicillin?', 6),
('What is the largest ocean?', 5),
('Who is the author of "The Iliad"?', 4),
('What is the main language spoken in Brazil?', 1),
('What is the chemical formula for table salt?', 7),
('Who is the founder of Microsoft?', 13),
('Who is the current Chancellor of Germany?', 14);

INSERT INTO Answer (text, isTrue, QuestionID) VALUES
('4', 1, 1),
('5', 0, 1),
('Paris', 1, 2),
('Berlin', 0, 2),
('William Shakespeare', 1, 3),
('Jane Austen', 0, 3),
('Mitochondria', 1, 4),
('Nucleus', 0, 4),
('George Washington', 1, 5),
('Abraham Lincoln', 0, 5),
('H2O', 1, 6),
('CO2', 0, 6),
('299,792,458 m/s', 1, 7),
('343 m/s', 0, 7),
('Leonardo da Vinci', 1, 8),
('Vincent van Gogh', 0, 8),
('Ice hockey', 1, 9),
('Soccer', 0, 9),
('Mount Everest', 1, 10),
('K2', 0, 10),
('100 degrees Celsius', 1, 11),
('0 degrees Celsius', 0, 11),
('Yen', 1, 12),
('Dollar', 0, 12),
('Ludwig van Beethoven', 1, 13),
('Wolfgang Amadeus Mozart', 0, 13),
('Alexander Fleming', 1, 14),
('Marie Curie', 0, 14),
('Pacific Ocean', 1, 15),
('Indian Ocean', 0, 15),
('Homer', 1, 16),
('Virgil', 0, 16),
('Portuguese', 1, 17),
('Spanish', 0, 17),
('NaCl', 1, 18),
('H2SO4', 0, 18),
('Bill Gates', 1, 19),
('Steve Jobs', 0, 19),
('Angela Merkel', 1, 20),
('Emmanuel Macron', 0, 20);

INSERT INTO Article (title, content, author, date, LanguageID, ImageID, LocationID) VALUES
('The Benefits of Exercise', 'Regular exercise has many benefits for your health...', 'John Doe', '2023-10-20', 1, 1, 1),
('The History of Ancient Rome', 'Ancient Rome was one of the most powerful civilizations...', 'Jane Smith', '2023-10-21', 4, 2, 3),
('Exploring the Wonders of the Great Barrier Reef', 'The Great Barrier Reef is the world''s largest coral reef system...', 'Michael Johnson', '2023-10-22', 1, 3, 7),
('A Guide to Making Authentic Italian Pizza', 'Italian pizza is renowned for its delicious taste and simple ingredients...', 'Maria Garcia', '2023-10-23', 4, 4, 4),
('The Impact of Global Warming on Polar Bears', 'Global warming has had a devastating impact on the habitat of polar bears...', 'David Lee', '2023-10-24', 1, 5, 9),
('The Beauty of Japanese Gardens', 'Japanese gardens are known for their tranquility and unique aesthetic...', 'Sophia Nguyen', '2023-10-25', 5, 6, 5),
('Understanding the Basics of Quantum Physics', 'Quantum physics is a fundamental branch of physics that studies the smallest particles...', 'Daniel Brown', '2023-10-26', 8, 7, 6),
('The Life and Legacy of Vincent van Gogh', 'Vincent van Gogh was a Dutch post-impressionist painter...', 'Emma Wilson', '2023-10-27', 15, 8, 2),
('The Evolution of Modern Computers', 'The evolution of modern computers has revolutionized the way we live and work...', 'William Thompson', '2023-10-28', 1, 9, 10),
('Exploring the Culture of India', 'India is known for its rich cultural heritage and diversity...', 'Sophie Baker', '2023-10-29', 10, 10, 11),
('The Impact of Ancient Greek Philosophy on Modern Thought', 'Ancient Greek philosophy has had a profound impact on modern thought and culture...', 'Michael Clark', '2023-10-30', 17, 11, 8),
('The Marvels of the Amazon Rainforest', 'The Amazon Rainforest is the largest rainforest in the world...', 'Olivia White', '2023-10-31', 1, 12, 14),
('The Rise of Artificial Intelligence in the 21st Century', 'Artificial intelligence has become an increasingly important part of modern society...', 'James Harris', '2023-11-01', 1, 13, 12),
('Understanding the Importance of Renewable Energy', 'Renewable energy sources are crucial for reducing our dependence on fossil fuels...', 'Ella Wilson', '2023-11-02', 1, 14, 16),
('Exploring the History of Ancient Egypt', 'Ancient Egypt was one of the most fascinating civilizations in history...', 'Alexander Johnson', '2023-11-03', 1, 15, 13),
('The Intriguing World of Cryptocurrencies', 'Cryptocurrencies have revolutionized the way we think about money and transactions...', 'Isabella Smith', '2023-11-04', 1, 16, 17),
('The Beauty of French Cuisine', 'French cuisine is known for its exquisite flavors and elegant presentation...', 'Thomas Garcia', '2023-11-05', 3, 17, 15),
('The Impact of Shakespearean Plays on Literature', 'Shakespearean plays have had a lasting impact on the world of literature...', 'Amelia Brown', '2023-11-06', 1, 18, 18),
('Exploring the History of the Chinese Dynasties', 'The history of the Chinese dynasties is rich and complex...', 'Oliver Johnson', '2023-11-07', 7, 19, 19),
('The Fascinating World of Marine Biology', 'Marine biology is the study of marine organisms and their interactions with the environment...', 'Charlotte Davis', '2023-11-08', 1, 20, 16);

INSERT INTO Role (name) VALUES
('Guest'),
('User'),
('Viewer'),
('Contributor'),
('Author'),
('Editor'),
('Moderator'),
('Manager'),
('Admin');

INSERT INTO Person (username, firstname, lastname, email, birthdate, hash, sex, LanguageID, LocationID, RoleID) VALUES
('john_doe', 'John', 'Doe', 'john_doe@example.com', '1990-05-12', 'password123', 'Male', 1, 1, 1),
('jane_smith', 'Jane', 'Smith', 'jane_smith@example.com', '1985-09-20', 'password456', 'Female', 2, 3, 3),
('michael_johnson', 'Michael', 'Johnson', 'michael_johnson@example.com', '1992-02-15', 'password789', 'Male', 3, 7, 4),
('maria_garcia', 'Maria', 'Garcia', 'maria_garcia@example.com', '1994-07-30', 'passwordabc', 'Female', 4, 4, 5),
('david_lee', 'David', 'Lee', 'david_lee@example.com', '1991-11-08', 'passworddef', 'Male', 1, 9, 2),
('sophia_nguyen', 'Sophia', 'Nguyen', 'sophia_nguyen@example.com', '1988-04-25', 'passwordghi', 'Female', 5, 5, 3),
('daniel_brown', 'Daniel', 'Brown', 'daniel_brown@example.com', '1987-06-18', 'passwordjkl', 'Male', 6, 6, 4),
('emma_wilson', 'Emma', 'Wilson', 'emma_wilson@example.com', '1993-08-22', 'passwordmno', 'Female', 7, 2, 5),
('william_thompson', 'William', 'Thompson', 'william_thompson@example.com', '1990-10-10', 'passwordpqr', 'Male', 1, 10, 6),
('sophie_baker', 'Sophie', 'Baker', 'sophie_baker@example.com', '1989-12-28', 'passwordstu', 'Female', 2, 11, 7),
('michael_clark', 'Michael', 'Clark', 'michael_clark@example.com', '1992-03-17', 'passwordvwx', 'Male', 3, 8, 8),
('olivia_white', 'Olivia', 'White', 'olivia_white@example.com', '1991-07-14', 'passwordyz', 'Female', 1, 14, 9),
('james_harris', 'James', 'Harris', 'james_harris@example.com', '1986-11-29', 'password1234', 'Male', 1, 12, 2),
('ella_wilson', 'Ella', 'Wilson', 'ella_wilson@example.com', '1995-01-05', 'password5678', 'Female', 1, 13, 2),
('alexander_johnson', 'Alexander', 'Johnson', 'alexander_johnson@example.com', '1994-04-02', 'password9012', 'Male', 1, 14, 3),
('isabella_smith', 'Isabella', 'Smith', 'isabella_smith@example.com', '1987-12-10', 'password3456', 'Female', 1, 16, 4),
('thomas_garcia', 'Thomas', 'Garcia', 'thomas_garcia@example.com', '1993-02-25', 'password7890', 'Male', 3, 17, 5),
('amelia_brown', 'Amelia', 'Brown', 'amelia_brown@example.com', '1990-06-14', 'password12345', 'Female', 1, 18, 6),
('oliver_johnson', 'Oliver', 'Johnson', 'oliver_johnson@example.com', '1989-09-27', 'password67890', 'Male', 7, 19, 7),
('charlotte_davis', 'Charlotte', 'Davis', 'charlotte_davis@example.com', '1992-04-30', 'password23456', 'Female', 1, 15, 8);

INSERT INTO Session (DeviceID, PersonID) VALUES
('device123', 10),
('device456', 9),
('device789', 8),
('deviceabc', 7),
('devicedef', 6),
('deviceghi', 5),
('devicejkl', 4),
('devicemno', 3),
('devicepqr', 2),
('devicestu', 1);

INSERT INTO Liked (PersonID, ArticleID) VALUES
(10, 1),
(9, 2),
(8, 3),
(7, 4),
(6, 5),
(5, 6),
(4, 7),
(3, 8),
(2, 9),
(1, 10);

INSERT INTO HasSeen (PersonID, ArticleID) VALUES
(1, 11),
(2, 12),
(3, 13),
(4, 14),
(5, 15),
(6, 16),
(7, 17),
(8, 18),
(9, 19),
(10, 20);

INSERT INTO HasDone (PersonID, QuizID, score) VALUES
(1, 1, 18),
(2, 2, 22),
(3, 3, 27),
(4, 4, 13),
(5, 5, 20),
(6, 6, 18),
(7, 7, 25),
(8, 8, 30),
(9, 9, 16),
(10, 10, 19);

INSERT INTO Answered (PersonID, QuestionID, correctAnswerGiven) VALUES
(1, 1, 1),
(2, 2, 1),
(3, 3, 1),
(4, 4, 1),
(5, 5, 1),
(6, 6, 1),
(7, 7, 1),
(8, 8, 1),
(9, 9, 1),
(10, 10, 1);